# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 84554982cba335689990aa4921d4d8f53da36aaa9c957bc5aa767bb2d3799412bdebc1d2aacdd7c933570f0420af3a47fcc3b60ee49632d87b0b173d7a87db1e

test:
  secret_key_base: 1f790473cafa4900bee3a7d13d49db0a31f61301bc27a67eb45f3a19459465e3099515a7f49fb3014b54d8e9a6ec182e52fc6d93ec491203f2cf493f044bf6c2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
